# This workflow will build a package using Maven and then archive it as build artifact
# in case when tag is pushed it will create new Release entry instead

name: "Maven Package Artifact"

on: "push"

jobs:
  build:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"

    steps:
    - uses: "actions/checkout@v2"
    - name: "Set up JDK 17"
      uses: "actions/setup-java@v2"
      with:
        java-version: "17"
        distribution: "temurin"

    - name: "Build package"
      run: "mvn --batch-mode package"

    - name: "Archive jar"
      uses: "actions/upload-artifact@v2"
      if: "! startsWith(github.ref, 'refs/tags')"
      with:
        path: "target/Hibernate-*.jar"


    - name: "Release"
      uses: "softprops/action-gh-release@v1"
      if: "startsWith(github.ref, 'refs/tags')"
      with:
        files: "target/Hibernate-*.jar"
        fail_on_unmatched_files: true
        generate_release_notes: true
