# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build package
      run: |
        mvn --batch-mode package
        pwd
        ls -lah
        ls -lah target/

    - name: Publish to GitHub Packages
      run: mvn --batch-mode -DaltDeploymentRepository="${REPO}" -DaltReleaseDeploymentRepository="${REPO}" -DaltSnapshotDeploymentRepository="${REPO}" -Dmaven.install.skip=true -s $GITHUB_WORKSPACE/settings.xml deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}
        REPO: "github::default::https://maven.pkg.github.com/${{ github.repository }}"
